<?php

namespace Tests;

use Language\Core\Config;

class ConfigTest extends \PHPUnit_Framework_TestCase
{

    protected $config;

    public function setUp()
    {
        parent::setUp();
        $home = __DIR__ . '/..';

        $rotPath = '{"system": {
            "paths": {"root": "' . $home . '/testdir"}
        }}';
        $this->config = new Config($home . '/etc/config.json',$rotPath);
    }

    /**
     * Test Config
     */
    public function testBaseInterfaceTrue()
    {
        $this->assertRegExp('/testdir/', $this->config->get('system.paths.root'));
        $this->assertStringEndsWith('/testdir', $this->config->get('system.paths.root'));
        $this->assertNotEmpty($this->config->get('system.log.file'));
        $this->assertTrue(is_array($this->config->get('system.translated_applications')));
    }

    /**
     * @return mixed
     */
    public function testConfigFunctions()
    {
        $this->assertMethodExist($this->config, 'get');
        $this->assertMethodExist($this->config, 'set');
        $this->assertMethodExist($this->config, 'add');
        $this->assertMethodNotExist($this->config, 'test');
    }

    /**
     * Assert that a class has a method
     *
     * @param $class
     * @param string $method name of the searched method
     * @throws ReflectionException if $class don't exist
     * @throws PHPUnit_Framework_ExpectationFailedException if a method isn't found
     */
    protected function assertMethodExist($class, $method) {
        $oReflectionClass = new \ReflectionClass($class);
        $this->assertTrue($oReflectionClass->hasMethod($method));
    }

    /**
     * @param $class
     * @param $method string
     */
    protected function assertMethodNotExist($class, $method) {
        $oReflectionClass = new \ReflectionClass($class);
        $this->assertFalse($oReflectionClass->hasMethod($method));
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
